### ISSUE TITLE
Search - Pollutant Releases

### ISSUE THREAD

**Issue by priisager1** [eea/eprtr2#15]
The pollutant Release search is not fully implemented (http://prtrproto.cloudapp.net/#/pollutantreleases).  

Compare with original: http://prtr.ec.europa.eu/PollutantReleases.aspx and implement the missing parts (f.ex. "Areas" and "Area Comparison"

**Comment by thomasAtkins12** [comment]
Is implemented but the link to Time Series and link parameters needs to be added
